#!/bin/sh
# A quick and easy way to run the reference checker on some standalone code.
# If you set the CLASSPATH environment variable it will ues it, adding its own entries to that list.
# To integrate the checker into a more complex build, reading the below should give you what you need to know.

dir=$(dirname $0)
ourclasspath="$dir/../jspecify/build/libs/jspecify-0.0.0-SNAPSHOT.jar:$dir/build/libs/jspecify-reference-checker.jar"

export CLASSPATH="$ourclasspath:$CLASSPATH"

$dir/../checker-framework/checker/bin/javac \
  -processorpath "$ourclasspath" \
  -processor com.google.jspecify.nullness.NullSpecChecker \
  -AcheckImpl \
  -AassumePure \
  -AsuppressWarnings=contracts.conditional.postcondition.false.methodref,contracts.conditional.postcondition.false.override,contracts.conditional.postcondition.true.methodref,contracts.conditional.postcondition.true.override,purity.methodref,purity.overriding,type.anno.before.decl.anno,type.anno.before.modifier \
  "$@"
